### ISSUE TITLE
Nav Bar Color

### ISSUE THREAD

**Issue by yarodevuci** [NSObjects/OMGImagePicker#1]
@NSObjects 
Is it possible to disable nav bar translucency and set color?
I tried standard methods but that did not help

**Comment by NSObjects** [comment]
@yarodevuci 
set nav bar color,
`navigationController.navigationBar.barTintColor = UIColor.green`

set translucency you can try 

```
 navigationController.navigationBar.isTranslucent = false
```

```
 navigationController.navigationBar.barTintColor = UIColor.brown
 navigationController.navigationBar.isTranslucent = false
```
![disable](http://linblog.oss-cn-hangzhou.aliyuncs.com/lALOla_8H2fNAeE_481_103.png_620x10000q90g.jpg)

` navigationController.navigationBar.isTranslucent = true`

![true](http://linblog.oss-cn-hangzhou.aliyuncs.com/lALOla_83GLNAfA_496_98.png_620x10000q90g.jpg)

**Comment by NSObjects** [comment]
@yarodevuci 
open OMGImagePickerViewController file ,go to viewSetup function,custom your want, enjoy~
![coded](http://linblog.oss-cn-hangzhou.aliyuncs.com/imagecode.png)

**Comment by yarodevuci** [comment]
@NSObjects 
Thanks!
