### ISSUE TITLE
OMGImagePicker crashes if user denies auth to photos

### ISSUE THREAD

**Issue by yarodevuci** [NSObjects/OMGImagePicker#2]
Hi. the title speaks for itself. It would be nice if you could implement something like standard image picker does. If user denied access to photos, picker could display an empty screen with lock icon and title
See example image below 

![simulator screen shot dec 30 2016 2 49 26 pm](https://cloud.githubusercontent.com/assets/13408859/21573903/2eb747cc-ce9f-11e6-9296-3a8f52f3da2c.png)

**Comment by NSObjects** [comment]
At new version , i add this view ,you can try.

**Comment by yarodevuci** [comment]
@NSObjects Sounds good. Thank you! Post here once new version is released 👍

**Comment by NSObjects** [comment]
@yarodevuci 
1.0.1 version added this Feature,

**Comment by yarodevuci** [comment]
@NSObjects looks good!
But what can I change to make that `Enable` button work on iOS 8 ? 
iOS 10 is working
